version: "3.9"

name: protegeme
services:
  api-auth:
    build:
      context: ./api-auth
      dockerfile: Dockerfile
    image: protegeme/api-auth:latest
    env_file:
      - ./api-auth/.env
    ports:
      - "4001:4001"
    restart: unless-stopped
    networks: [protegeme-net]

  api-incidents:
    build:
      context: ./api-incidents
      dockerfile: Dockerfile
    image: protegeme/api-incidents:latest
    env_file:
      - ./api-incidents/.env
    ports:
      - "4002:4002"
    restart: unless-stopped
    networks: [protegeme-net]

  api-authorizations:
    build:
      context: ./api-authorizations
      dockerfile: Dockerfile
    image: protegeme/api-authorizations:latest
    env_file:
      - ./api-authorizations/.env
    ports:
      - "4003:4003"
    restart: unless-stopped
    networks: [protegeme-net]

  api-maintenance:
    build:
      context: ./api-maintenance
      dockerfile: Dockerfile
    image: protegeme/api-maintenance:latest
    env_file:
      - ./api-maintenance/.env
    ports:
      - "4004:4004"
    restart: unless-stopped
    networks: [protegeme-net]
    volumes:
      - ./data/uploads/maintenance:/app/uploads  # UPLOAD_DIR=./uploads

  api-vehicle:
    build:
      context: ./api-vehicle
      dockerfile: Dockerfile
    image: protegeme/api-vehicle:latest
    env_file:
      - ./api-vehicle/.env
    ports:
      - "4005:4005"
    restart: unless-stopped
    networks: [protegeme-net]
    volumes:
      - ./data/uploads/vehicle:/app/uploads      # UPLOAD_DIR=./uploads

  api-drivers:
    build:
      context: ./api-driver
      dockerfile: Dockerfile
    image: protegeme/api-driver:latest
    env_file:
      - ./api-driver/.env
    ports:
      - "4006:4006"
    restart: unless-stopped
    networks: [protegeme-net]

  web:
    build:
      context: ./protegeme-app
      dockerfile: Dockerfile
    image: protegeme/web:latest
    ports:
      - "5173:80"
    restart: unless-stopped
    networks: [protegeme-net]
  minio:
    image: minio/minio:latest
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    volumes:
      - ./data/minio:/data
    ports:
      - "9000:9000"   # API S3
      - "9001:9001"   # Consola Web
    restart: unless-stopped
    networks: [protegeme-net]

  # init de bucket (one-shot)
  minio-mc:
    image: minio/mc:latest
    depends_on:
      - minio
    entrypoint: ["/bin/sh","-c"]
    command: >
      mc alias set local http://minio:9000 ${MINIO_ROOT_USER} ${MINIO_ROOT_PASSWORD} &&
      mc mb -p local/${MINIO_BUCKET} || true &&
      mc anonymous set download local/${MINIO_BUCKET} || true
    networks: [protegeme-net]
    restart: "no"
networks:
  protegeme-net:
    driver: bridge
