services:
  - type: web
    name: ms-auth
    env: node
    rootDir: api-auth
    plan: free
    autoDeploy: true
    buildCommand: "npm ci && npm i -D @nestjs/cli && npm run build"
    startCommand: "node dist/main.js"
    healthCheckPath: "/health"
    envVars:
      - key: NODE_ENV
        value: production
      - key: NODE_VERSION
        value: "20"
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: JWT_EXPIRES
        sync: false
      - key: CORS_ALLOWED
        value: "https://protegemesicov-q7ei.vercel.app"

  - type: web
    name: ms-authorizations
    env: node
    rootDir: api-authorizations
    plan: free
    autoDeploy: true
    buildCommand: "npm ci && npm i -D @nestjs/cli && npm run build"
    startCommand: "node dist/main.js"
    healthCheckPath: "/health"
    envVars:
      - key: NODE_ENV
        value: production
      - key: NODE_VERSION
        value: "20"
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: CORS_ALLOWED
        value: "https://protegemesicov-q7ei.vercel.app"

  - type: web
    name: ms-driver
    env: node
    rootDir: api-driver
    plan: free
    autoDeploy: true
    buildCommand: "npm ci && npm i -D @nestjs/cli && npm run build"
    startCommand: "node dist/main.js"
    healthCheckPath: "/health"
    envVars:
      - key: NODE_ENV
        value: production
      - key: NODE_VERSION
        value: "20"
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: CORS_ALLOWED
        value: "https://protegemesicov-q7ei.vercel.app"

  - type: web
    name: ms-incidents
    env: node
    rootDir: api-incidents
    plan: free
    autoDeploy: true
    buildCommand: "npm ci && npm i -D @nestjs/cli && npm run build"
    startCommand: "node dist/main.js"
    healthCheckPath: "/health"
    envVars:
      - key: NODE_ENV
        value: production
      - key: NODE_VERSION
        value: "20"
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: CORS_ALLOWED
        value: "https://protegemesicov-q7ei.vercel.app"

  - type: web
    name: ms-maintenance
    env: node
    rootDir: api-maintenance
    plan: free
    autoDeploy: true
    buildCommand: "npm ci && npm i -D @nestjs/cli && npm run build"
    startCommand: "node dist/main.js"
    healthCheckPath: "/health"
    envVars:
      - key: NODE_ENV
        value: production
      - key: NODE_VERSION
        value: "20"
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: CORS_ALLOWED
        value: "https://protegemesicov-q7ei.vercel.app"
      - key: UPLOAD_DIR
        value: "./uploads"

  - type: web
    name: ms-vehicle
    env: node
    rootDir: api-vehicle
    plan: free
    autoDeploy: true
    buildCommand: "npm ci && npm i -D @nestjs/cli && npm run build"
    startCommand: "node dist/main.js"
    healthCheckPath: "/health"
    envVars:
      - key: NODE_ENV
        value: production
      - key: NODE_VERSION
        value: "20"
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: CORS_ALLOWED
        value: "https://protegemesicov-q7ei.vercel.app"
      - key: UPLOAD_DIR
        value: "./uploads"
